name: Build and Deploy (PROD)
on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
    paths-ignore:
      - "README.md"
      - ".vscode/**"
      - "assets/**"
      - "deploy/bicep-dev/**"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  set-env:
    name: Set Environment Variables
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.main.outputs.version }}
      created: ${{ steps.main.outputs.created }}
      repository: ${{ steps.main.outputs.repository }}

    steps:
      - id: main
        run: |
          echo ::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-7)
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=repository::$GITHUB_REPOSITORY

  package-services:
    runs-on: ubuntu-latest
    needs: set-env
    permissions:
      contents: read
      packages: write

    outputs:
      api-image: ${{ steps.image-tag.outputs.image-album-api }}
      ui-image: ${{ steps.image-tag.outputs.image-album-viewer }}

    strategy:
      matrix:
        services:
          [
            { "appName": "album-api", "directory": "./album-api" },
            { "appName": "album-viewer", "directory": "./album-viewer" },
          ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ needs.set-env.outputs.repository }}/${{ matrix.services.appName }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=sha
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.services.directory }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Output image tag
        id: image-tag
        run: |
          echo ::set-output name=image-${{ matrix.services.appName }}::${{ env.REGISTRY }}/$GITHUB_REPOSITORY/${{ matrix.services.appName }}:sha-${{ needs.set-env.outputs.version }} | tr '[:upper:]' '[:lower:]'

  deploy:
    if: github.repository != 'Azure-samples/containerapps-dapralbums'
    runs-on: ubuntu-latest
    concurrency:
      group: prod
      cancel-in-progress: true    
    needs: [package-services]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy bicep
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az group create -g ${{ secrets.RG_PROD }}  -l eastus
            az deployment group create -g ${{ secrets.RG_PROD }} -f ./deploy/bicep-prod/main.bicep --parameters \
            apiImage='${{ needs.package-services.outputs.api-image }}' \
            viewerImage='${{ needs.package-services.outputs.ui-image }}' \
            registryServer=${{ env.REGISTRY }} \
            registryUsername=${{ github.actor }} \
            registryPassword=${{ secrets.GH_PAT }}

  test:
    needs: deploy
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: e2e-tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get container app FQDN's'
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |
            az extension add --name containerapp
            $baseUrl = "https://$(az containerapp show -g ${{ secrets.RG_PROD }} -n album-viewer -o tsv --query properties.configuration.ingress.fqdn)"
            $apiUrl = "https://$(az containerapp show -g ${{ secrets.RG_PROD }} -n album-api -o tsv --query properties.configuration.ingress.fqdn)"
            echo "BASE_URL=$baseUrl" "API_URL=$apiUrl" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        
      - name: Run Playwright tests
        run: |
          baseUrl=${{ env.BASE_URL }} apiUrl=${{ env.API_URL }} HOME=/root npx playwright test

      - name: Create test summary
        uses: test-summary/action@dist
        if: always()
        with:
          paths: src/Web/E2E/test-results/junit.xml

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: src/Web/E2E/playwright-report/
          retention-days: 30